### ISSUE TITLE
Dev CoP - All Presentation/Workshop Dates

### ISSUE THREAD

**Issue by ahmad-shahid** [esdc-devcop/strategy#42]
Session | Pres/Workshop | Date | Time | Topic  
-- | -- | -- | -- | --
Session   1 | Presentation | Tuesday,   September 10th | 10am | #1 Move Source Control to Git
  | Workshop | Tuesday,   September 17th | 12pm | #1 Move Source Control to Git
Session   2 | Presentation | Tuesday,   October 15th | 10am | #10 Make use of the GitFlow branching model
  | Workshop | Monday   October 21st | 12pm | #10 Make use of the GitFlow branching model
Session   3 | Presentation | Tuesday   November 12th | 10am | TBD
  | Workshop | Tuesday   November 19th | 12pm | TBD
Session   4 | Presentation | Tuesday   December 3rd  | 10am | TBD
  | Workshop | Tuesday   December 10th | 12pm | TBD
Session   5 | Presentation | Tuesday   January 14th | 10am | TBD
  | Workshop | Tuesday   January 21st | 12pm | TBD
Session   6 | Presentation | Tuesday   February 4th | 10am | TBD
  | Workshop | Tuesday   February 11th | 12pm | TBD
Session   7 | Presentation | Tuesday   March 3rd | 10am | TBD
  | Workshop | Tuesday   March 10th | 12pm | TBD
Session   8 | Presentation | Tuesday   April 7th | 10am | TBD
  | Workshop | Tuesday   April 14th | 12pm | TBD
Session   9 | Presentation | Tuesday   May 5th | 10am | TBD
  | Workshop | Tuesday   May 12th | 12pm | TBD
Session   10 | Presentation | Tuesday   June 2nd | 10am | TBD
  | Workshop | Tuesday   June 9th | 12pm | TBD

**Comment by s-laugh** [comment]
Let's get this documented in the repo code (md)! .

Also I think you accidentally linked issues trying to number the sessions.

Can we also add columns for time, and topic references (issue & guides) to these?

**Comment by ahmad-shahid** [comment]
oh ya just noticed!
